### ISSUE TITLE
guld dist error - file not found 

### ISSUE THREAD

**Issue by Mortenagoda** [Nykredit/gript#65]
gulp dist
fails with "File not found..."

It seams the directory has an extra "target" folder, "xp2-client\target\target\tmp\styles\app.css".

The file is found in "xp2-client\target\tmp\styles\app.css".

```
[09:45:08] gulp-debug: app\index.html
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Error: File not found with singular glob: C:\projects\xp2-client\target\target\tmp\styles\app.css
    at DestroyableTransform.<anonymous> (C:\projects\xp2-client\node_modules\gript\node_modules\gulp-useref\lib\streamManager.js:90:36)
    at emitOne (events.js:82:20)
    at DestroyableTransform.emit (events.js:169:7)
    at emitOne (events.js:77:13)
    at DestroyableTransform.emit (events.js:169:7)
    at Glob.<anonymous> (C:\projects\xp2-client\node_modules\gript\node_modules\gulp-useref\node_modules\vinyl-fs\node_modules\glob-stream\index.js:38:16)
    at Glob.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Glob.emit (events.js:169:7)
    at Glob._finish (C:\projects\xp2-client\node_modules\gript\node_modules\gulp-useref\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js
:172:8)
    at done (C:\projects\xp2-client\node_modules\gript\node_modules\gulp-useref\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:159:12)

    at Glob._processSimple2 (C:\projects\xp2-client\node_modules\gript\node_modules\gulp-useref\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob
\glob.js:652:12)
    at C:\projects\xp2-client\node_modules\gript\node_modules\gulp-useref\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:640:10
    at Glob._stat2 (C:\projects\xp2-client\node_modules\gript\node_modules\gulp-useref\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:
736:12)
    at lstatcb_ (C:\projects\xp2-client\node_modules\gript\node_modules\gulp-useref\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:728
:12)
    at RES (C:\projects\xp2-client\node_modules\gript\node_modules\gulp-useref\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\node_modules\inf
light\inflight.js:23:14)
    at f (C:\projects\xp2-client\node_modules\gript\node_modules\gulp-useref\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\node_modules\once\
once.js:17:25)
    at FSReqWrap.oncomplete (fs.js:82:15)

[xp2-client] C:\projects\xp2-client>
```

**Comment by jotka** [comment]
gript version number 0.0.45 ?

**Comment by Mortenagoda** [comment]
Using 0.0.43. Will try the new one.

**Comment by jotka** [comment]
can not reproduce on 0.0.45, everything seems fine. Please do the 'clean' first.

**Comment by Mortenagoda** [comment]
Okay, this was not an issue in gript. Closing issue.
