### ISSUE TITLE
Errors when upgrading to 0.0.45

### ISSUE THREAD

**Issue by jhpe** [Nykredit/gript#66]
Hi

We tried upgrading to version 0.0.45 to use some of the new features :) However, running gulp after upgrading our dependency to 0.0.45 gives the following:

1. Plugins error
=============

Test task fails with:

    [10:47:29] Starting 'test'...
    07 04 2016 10:47:30.208:WARN [reporter]: Can not load "junit", it is not registered!
      Perhaps you are missing some plugin?
    [10:47:30] 'test' errored after 375 ms
    [10:47:30] Error: No provider for "framework:angular-filesort"! (Resolving: framework:angular-filesort)
        at error (C:\projects\bankshift\node_modules\gript\node_modules\karma\node_modules\di\lib\injector.js:22:12)
        at Object.parent.get (C:\projects\bankshift\node_modules\gript\node_modules\karma\node_modules\di\lib\injector.js:9:13)
        at get (C:\projects\bankshift\node_modules\gript\node_modules\karma\node_modules\di\lib\injector.js:54:19)
        at C:\projects\bankshift\node_modules\gript\node_modules\karma\lib\server.js:137:20
        at Array.forEach (native)
        at Server._start (C:\projects\bankshift\node_modules\gript\node_modules\karma\lib\server.js:136:21)
        at invoke (C:\projects\bankshift\node_modules\gript\node_modules\karma\node_modules\di\lib\injector.js:75:15)
        at Server.start (C:\projects\bankshift\node_modules\gript\node_modules\karma\lib\server.js:101:18)
        at Gulp.<anonymous> (C:\projects\bankshift\node_modules\gript\tasks\test.gulp.js:24:12)
        at module.exports (C:\projects\bankshift\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
        at Gulp.Orchestrator._runTask (C:\projects\bankshift\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
        at Gulp.Orchestrator._runStep (C:\projects\bankshift\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
        at C:\projects\bankshift\node_modules\gulp\node_modules\orchestrator\index.js:279:18
        at finish (C:\projects\bankshift\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
        at C:\projects\bankshift\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:52:4
        at f (C:\projects\bankshift\node_modules\gulp\node_modules\orchestrator\node_modules\end-of-stream\node_modules\once\once.js:17:25)
        at DestroyableTransform.onend (C:\projects\bankshift\node_modules\gulp\node_modules\orchestrator\node_modules\end-of-stream\index.js:31:18)
        at emitNone (events.js:72:20)
        at DestroyableTransform.emit (events.js:166:7)
        at endReadableNT (C:\projects\bankshift\node_modules\gript\node_modules\gulp-filenames\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:944:12)
        at afterTick (C:\projects\bankshift\node_modules\gript\node_modules\gulp-filenames\node_modules\through2\node_modules\readable-stream\node_modules\process-nextick-args\index.js:11:8)
        at doNTCallback0 (node.js:419:9)
    [10:47:30] Error in plugin 'run-sequence'
    Message:
        An error occured in task 'test'.
    [10:47:30] 'inject' errored after 4.09 s
    [10:47:30] Error in plugin 'run-sequence'

Can be fixed by adding the required plugins to tasks/karma.conf.js:

        plugins: [
            'karma-jasmine',
            'karma-angular-filesort',
            'karma-phantomjs-launcher',
            'karma-junit-reporter',
            'karma-coverage',
            'karma-ng-html2js-preprocessor'
        ]

2. Missing bind on Function prototype
=====================================

After fixing missing plugins the 'test' task fails with the following when using Angular 1.5 (also reported in issue #63):

    07 04 2016 10:57:31.146:INFO [launcher]: Starting browser PhantomJS
    07 04 2016 10:57:31.910:INFO [PhantomJS 1.9.8 (Windows 7 0.0.0)]: Connected on socket /#46NNJYZj4AZqINZBAAAA with id 56746344
    PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR
      Error: [$injector:modulerr] Failed to instantiate module ng due to:
      TypeError: 'undefined' is not an object (evaluating 'Function.prototype.bind.apply')
          at instantiate (C:/projects/bankshift/bower_components/angular/angular.js:4640)
          at provider (C:/projects/bankshift/bower_components/angular/angular.js:4454)
          at C:/projects/bankshift/bower_components/angular/angular.js:365
          at forEach (C:/projects/bankshift/bower_components/angular/angular.js:335)
          at C:/projects/bankshift/bower_components/angular/angular.js:4444
          at ngModule (C:/projects/bankshift/bower_components/angular/angular.js:2494)
          at invoke (C:/projects/bankshift/bower_components/angular/angular.js:4625)
          at runInvokeQueue (C:/projects/bankshift/bower_components/angular/angular.js:4518)
          at C:/projects/bankshift/bower_components/angular/angular.js:4527
          at forEach (C:/projects/bankshift/bower_components/angular/angular.js:321)
          at loadModules (C:/projects/bankshift/bower_components/angular/angular.js:4550)
          at createInjector (C:/projects/bankshift/bower_components/angular/angular.js:4430)
          at C:/projects/bankshift/app/app.js:73
          at C:/projects/bankshift/app/app.js:82
          at C:/projects/bankshift/app/app.js:152
      http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=ng&p1=TypeError%3A%20'undefined'%20is%20not%20an%20object%20(evaluating%20'Function.prototype.bind.apply')%0A%20%20%20%20at%20instantiate%20(http%3A%2F%2Flocalhost%3A9876%2FC:/projects/bankshift%2Fbower_components%2Fangular%2Fangular.js%3Fe19a0bed71d517ca1f3d8098edb3d27e0966badd%3A4640)%0A%20%20%20%20at%20provider%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fbower_components%2Fangular%2Fangular.js%3Fe19a0bed71d517ca1f3d8098edb3d27e0966badd%3A4454)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fbower_components%2Fangular%2Fangular.js%3Fe19a0bed71d517ca1f3d8098edb3d27e0966badd%3A365%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fbower_components%2Fangular%2Fangular.js%3Fe19a0bed71d517ca1f3d8098edb3d27e0966badd%3A335)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fbower_components%2Fangular%2Fangular.js%3Fe19a0bed71d517ca1f3d8098edb3d27e0966badd%3A4444%0A%20%20%20%20at%20ngModule%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fbower_components%2Fangular%2Fangular.js%3Fe19a0bed71d517ca1f3d8098edb3d27e0966badd%3A2494)%0A%20%20%20%20at%20invoke%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fbower_components%2Fangular%2Fangular.js%3Fe19a0bed71d517ca1f3d8098edb3d27e0966badd%3A4625)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fbower_components%2Fangular%2Fangular.js%3Fe19a0bed71d517ca1f3d8098edb3d27e0966badd%3A4518)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fbower_components%2Fangular%2Fangular.js%3Fe19a0bed71d517ca1f3d8098edb3d27e0966badd%3A4527%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fbower_components%2Fangular%2Fangular.js%3Fe19a0bed71d517ca1f3d8098edb3d27e0966badd%3A321)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fbower_components%2Fangular%2Fangular.js%3Fe19a0bed71d517ca1f3d8098edb3d27e0966badd%3A4550)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fbower_components%2Fangular%2Fangular.js%3Fe19a0bed71d517ca1f3d8098edb3d27e0966badd%3A4430)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fapp%2Fapp.js%3Fe7cfa2cb2f038539aa9c139376e51d48fa0f2700%3A73%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fapp%2Fapp.js%3Fe7cfa2cb2f038539aa9c139376e51d48fa0f2700%3A82%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fapp%2Fapp.js%3Fe7cfa2cb2f038539aa9c139376e51d48fa0f2700%3A152
      at C:/projects/bankshift/bower_components/angular/angular.js:4548

Can be fixed by either upgrading to newer version of PhantonJS, or by using a polyfill:

    npm install --save-dev phantomjs-polyfill

Update 'get-sources' task to include the polyfill:

    return gulp.src(
        [
            path.join(paths.src.app, '../node_modules/phantomjs-polyfill/bind-polyfill.js'),
            path.join(paths.src.app, '**/*.js'),
            path.join(paths.target.tmp.js, '**/*.js'),
            path.join(paths.target.tmp.partials, '**/*.js')
        ], {base: '.'})

3. Missing dependency to Sinon
=========================

When running tests that use Sinon we get an error about:

    07 04 2016 11:52:17.020:WARN [watcher]: Pattern "C:/projects/bankshift/node_modules/gript/node_modules/sinon/pkg/sinon.js" does not match any file.
    PhantomJS 1.9.8 (Windows 7 0.0.0) UserInfo module should get default values initially FAILED
            ReferenceError: Can't find variable: sinon
                at C:/projects/bankshift/app/components/user-info-service/user-info-service_test.js:23
                at invoke (C:/projects/bankshift/bower_components/angular/angular.js:4625)
                at workFn (C:/projects/bankshift/bower_components/angular-mocks/angular-mocks.js:2933)
                at C:/projects/bankshift/bower_components/angular-mocks/angular-mocks.js:2902
                at C:/projects/bankshift/app/components/user-info-service/user-info-service_test.js:24
            undefined

It turns out that gript does not have a sinon.js where it expects it to be in the 'test' task:
```
    new Server({
                configFile: __dirname + '/karma.conf.js',
                files: bowerDeps.js.concat('node_modules/gript/node_modules/sinon/pkg/sinon.js', filenames.get('js')),
                singleRun: true
            }, function () {
                done();
            }).start();

```
You need to somehow make sure that Sinon is always present where you assume it is. Our temporary fix is to change the path to our own dependency to Sinon at `node_modules/sinon/pkg/sinon.js` but of course that is not a proper solution.

**Comment by jotka** [comment]
Hi @jhpe 

1. What exactly do you mean by this ? the current [tasks/karma.conf.js](https://github.com/Nykredit/gript/blob/master/tasks/karma.conf.js) contains all needed references: 

```
plugins: [
            'karma-jasmine',
            'karma-angular-filesort',
            'karma-phantomjs-launcher',
            'karma-junit-reporter',
            'karma-coverage',
            'karma-ng-html2js-preprocessor'
        ],
```

2. duplicate #63

3. the sinon.js is always available in the /node_modules/gript/node_modules/sinon/pkg/sinon.js in the projects I know that use gript, like mitnykredit, xp2-client, ssm-client etc.

**Comment by jhpe** [comment]
Hi,

1. I don't know the complete internals of Gript, but the karma.conf.js you link to is not the same that ends up in node_modules when you use Gript as a dependency. You can reproduce it with a minimal `package.json` 
```
    {
      "name": "test",
      "version": "0.0.1",
      "description": "Tool",
      "devDependencies": {
        "gript": "0.0.45"
        },
      "repository": {
        "type": "git",
        "url": "https://test.git"
      },
      "license": "MIT",
      "readme": "readme"
    }
```
and do `npm install`

2. I added a solution hoping it would be fixed quicker and to help other people having the same issue :)

3. If the project that depends on Gript already has a dependency to a suitable version of Sinon, then Sinon will not be added to Gript's node_modulues as the dependency is already met. You can  check this by adding sinon the the minimal `package.json` from above:
 ```
   {
      "name": "test",
      "version": "0.0.1",
      "description": "Tool",
      "devDependencies": {
        "gript": "0.0.45"
        },
      "repository": {
        "type": "git",
        "url": "https://test.git"
      },
      "license": "MIT",
      "readme": "readme"
    }
```

and do `npm install`

**Comment by jotka** [comment]
1. ok it's a bug, fix release today.

2. ok I understand, but do you need the dependency to `sinon.js` in your `package.json` ? 

note:
Please do not combine unrelated issues in one github ticket. It's tricky to reply :)

**Comment by jhpe** [comment]
1. Cool, thanks.
2. We can probably remove our own dependency to make it work, but other people will hit this bug again later. I think you can use something like `require.resolve()` to get the path of the module insteed of hardcoding the path.
3. The issues were all related to v. 0.0.45, that's why I did it like this, but ok :)

**Comment by jhpe** [comment]
I now realize that our issue with sinon is also reported with another solution in #42

**Comment by jotka** [comment]
3. No they are not :) but I will fix them of course anyway :)

Thanks
Jarek

Dnia 07.04.2016 o godz. 14:16 jhpe <notifications@github.com> napisał(a):

**Comment by jotka** [comment]
hi @jhpe 
Can you please try 0.0.46 ? Sinon is now being loaded as Karma plugin in `karma.conf.js`. The reference to absolute path to `sinon.js` in the `test` task is now removed.

Also, your nr 1 - "Plugins error" should be fine now.

**Comment by jotka** [comment]
phantom.js updated to 2.1 in 0.0.47

**Comment by jhpe** [comment]
Hi,
We have upgraded to 0.0.47 and everything looks ok. Thanks.
