### ISSUE TITLE
Gript proxy crashes

### ISSUE THREAD

**Issue by Mortenagoda** [Nykredit/gript#76]
In our current project we wan't to use the proxy. Unfortunately it fails.

The Gript sample application also fails when the proxy URL, localhost:8001 is loaded in the browser.

[11:17:44] Finished 'get-sources' after 64 ms
[11:17:44] Starting 'test'...
12 05 2016 11:17:47.987:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
12 05 2016 11:17:47.999:INFO [launcher]: Starting browser PhantomJS
12 05 2016 11:17:49.827:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket /#EZHKKNZ05xQYr8ykAAAA with id 14561805
PhantomJS 2.1.1 (Windows 7 0.0.0): Executed 2 of 2 SUCCESS (0.153 secs / 0.029 secs)
[11:17:55] Finished 'test' after 10 s
[11:17:55] Starting 'inject-js'...
[11:17:55] gulp-inject 8 files into index.html.
[11:17:55] Finished 'inject-js' after 97 ms
[11:17:55] Finished 'inject' after 19 s
[11:17:55] Starting 'build'...
[11:17:55] Finished 'build' after 26 µs
[11:17:55] Starting 'mocks'...
[11:17:55] Finished 'mocks' after 339 µs
[11:17:55] Starting 'server'...
[11:17:55] Finished 'server' after 72 ms
[11:17:55] Starting 'proxy'...
[11:17:55] Starting proxy on port 8001, target url: http://gript, host header: gript
[11:17:55] Finished 'proxy' after 32 ms
[11:17:55] Starting 'watch'...
[11:17:55] Finished 'watch' after 46 ms
[11:17:55] Server started http://localhost:8080
[11:17:55] LiveReload started on port 35729
_http_outgoing.js:333
    throw new Error('`value` required in setHeader("' + name + '", value).');
    ^

Error: `value` required in setHeader("Host", value).
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at ProxyServer.<anonymous> (C:\projects\gript\tasks\proxy.gulp.js:34:30)
    at ProxyServer.emit (C:\projects\gript\node_modules\http-proxy\node_modules\eventemitter3\index.js:119:35)
    at ClientRequest.<anonymous> (C:\projects\gript\node_modules\http-proxy\lib\http-proxy\passes\web-incoming.js:114:27)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:484:7)
    at onSocketNT (_http_client.js:496:5)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

[gript] C:\projects\gript>

**Comment by jotka** [comment]
fixed and published as 0.0.51
